#############################################################################
# Makefile for building: QMineSweeper
# Generated by qmake (2.01a) (Qt 4.6.2) on: Fri Dec 31 05:26:28 2010
# Project:  QMineSweeper.pro
# Template: app
# Command: /usr/bin/qmake-qt4 -spec /usr/share/qt4/mkspecs/linux-g++ -unix CONFIG+=debug -o Makefile QMineSweeper.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -I.
LINK          = g++
LFLAGS        = 
LIBS          = $(SUBLIBS)  -L/usr/lib -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake-qt4
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = Cell.cpp \
		Board.cpp \
		util.cpp \
		GameLogic.cpp \
		NormalGameLogic.cpp \
		test.cpp \
		TextUI.cpp \
		MainWindow.cpp \
		MsButton.cpp \
		IconFactory.cpp \
		main.cpp \
		NewGameDialog.cpp \
		Player.cpp \
		HumanPlayer.cpp \
		CompeteGameLogic.cpp \
		AIPlayer.cpp moc_GameLogic.cpp \
		moc_MainWindow.cpp \
		moc_MsButton.cpp \
		moc_NewGameDialog.cpp \
		moc_AIPlayer.cpp \
		qrc_resource.cpp
OBJECTS       = Cell.o \
		Board.o \
		util.o \
		GameLogic.o \
		NormalGameLogic.o \
		test.o \
		TextUI.o \
		MainWindow.o \
		MsButton.o \
		IconFactory.o \
		main.o \
		NewGameDialog.o \
		Player.o \
		HumanPlayer.o \
		CompeteGameLogic.o \
		AIPlayer.o \
		moc_GameLogic.o \
		moc_MainWindow.o \
		moc_MsButton.o \
		moc_NewGameDialog.o \
		moc_AIPlayer.o \
		qrc_resource.o
DIST          = /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		QMineSweeper.pro
QMAKE_TARGET  = QMineSweeper
DESTDIR       = 
TARGET        = QMineSweeper

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_NewGameDialog.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: QMineSweeper.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/libQtGui.prl \
		/usr/lib/libQtCore.prl
	$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ -unix CONFIG+=debug -o Makefile QMineSweeper.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/debug.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/libQtGui.prl:
/usr/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ -unix CONFIG+=debug -o Makefile QMineSweeper.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/QMineSweeper1.0.0 || $(MKDIR) .tmp/QMineSweeper1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/QMineSweeper1.0.0/ && $(COPY_FILE) --parents GameLogic.h Cell.h Board.h util.h NormalGameLogic.h MainWindow.h MsButton.h IconFactory.h NewGameDialog.h ui_NewGameDialog.h CompeteGameLogic.h HumanPlayer.h Player.h AIPlayer.h .tmp/QMineSweeper1.0.0/ && $(COPY_FILE) --parents resource.qrc .tmp/QMineSweeper1.0.0/ && $(COPY_FILE) --parents Cell.cpp Board.cpp util.cpp GameLogic.cpp NormalGameLogic.cpp test.cpp TextUI.cpp MainWindow.cpp MsButton.cpp IconFactory.cpp main.cpp NewGameDialog.cpp Player.cpp HumanPlayer.cpp CompeteGameLogic.cpp AIPlayer.cpp .tmp/QMineSweeper1.0.0/ && $(COPY_FILE) --parents NewGameDialog.ui .tmp/QMineSweeper1.0.0/ && (cd `dirname .tmp/QMineSweeper1.0.0` && $(TAR) QMineSweeper1.0.0.tar QMineSweeper1.0.0 && $(COMPRESS) QMineSweeper1.0.0.tar) && $(MOVE) `dirname .tmp/QMineSweeper1.0.0`/QMineSweeper1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/QMineSweeper1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_GameLogic.cpp moc_MainWindow.cpp moc_MsButton.cpp moc_NewGameDialog.cpp moc_AIPlayer.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_GameLogic.cpp moc_MainWindow.cpp moc_MsButton.cpp moc_NewGameDialog.cpp moc_AIPlayer.cpp
moc_GameLogic.cpp: Board.h \
		Cell.h \
		util.h \
		GameLogic.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) GameLogic.h -o moc_GameLogic.cpp

moc_MainWindow.cpp: GameLogic.h \
		Board.h \
		Cell.h \
		util.h \
		MsButton.h \
		Player.h \
		MainWindow.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) MainWindow.h -o moc_MainWindow.cpp

moc_MsButton.cpp: GameLogic.h \
		Board.h \
		Cell.h \
		util.h \
		MsButton.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) MsButton.h -o moc_MsButton.cpp

moc_NewGameDialog.cpp: ui_NewGameDialog.h \
		NewGameDialog.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) NewGameDialog.h -o moc_NewGameDialog.cpp

moc_AIPlayer.cpp: Player.h \
		GameLogic.h \
		Board.h \
		Cell.h \
		util.h \
		AIPlayer.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) AIPlayer.h -o moc_AIPlayer.cpp

compiler_rcc_make_all: qrc_resource.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_resource.cpp
qrc_resource.cpp: resource.qrc \
		img/new.png \
		img/logo.png \
		img/0.png \
		img/MARKED.png \
		img/1.png \
		img/2.png \
		img/3.png \
		img/quit.png \
		img/4.png \
		img/5.png \
		img/6.png \
		img/7.png \
		img/MINE.png \
		img/8.png \
		img/UNKNOWN.png
	/usr/bin/rcc -name resource resource.qrc -o qrc_resource.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_NewGameDialog.h
compiler_uic_clean:
	-$(DEL_FILE) ui_NewGameDialog.h
ui_NewGameDialog.h: NewGameDialog.ui
	/usr/bin/uic-qt4 NewGameDialog.ui -o ui_NewGameDialog.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_uic_clean 

####### Compile

Cell.o: Cell.cpp Cell.h \
		util.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Cell.o Cell.cpp

Board.o: Board.cpp Board.h \
		Cell.h \
		util.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Board.o Board.cpp

util.o: util.cpp util.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o util.o util.cpp

GameLogic.o: GameLogic.cpp GameLogic.h \
		Board.h \
		Cell.h \
		util.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o GameLogic.o GameLogic.cpp

NormalGameLogic.o: NormalGameLogic.cpp NormalGameLogic.h \
		GameLogic.h \
		Board.h \
		Cell.h \
		util.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o NormalGameLogic.o NormalGameLogic.cpp

test.o: test.cpp Cell.h \
		util.h \
		Board.h \
		GameLogic.h \
		NormalGameLogic.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o test.o test.cpp

TextUI.o: TextUI.cpp NormalGameLogic.h \
		GameLogic.h \
		Board.h \
		Cell.h \
		util.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o TextUI.o TextUI.cpp

MainWindow.o: MainWindow.cpp MainWindow.h \
		GameLogic.h \
		Board.h \
		Cell.h \
		util.h \
		MsButton.h \
		Player.h \
		IconFactory.h \
		HumanPlayer.h \
		AIPlayer.h \
		NewGameDialog.h \
		ui_NewGameDialog.h \
		CompeteGameLogic.h \
		NormalGameLogic.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o MainWindow.o MainWindow.cpp

MsButton.o: MsButton.cpp MainWindow.h \
		GameLogic.h \
		Board.h \
		Cell.h \
		util.h \
		MsButton.h \
		Player.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o MsButton.o MsButton.cpp

IconFactory.o: IconFactory.cpp IconFactory.h \
		Cell.h \
		util.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o IconFactory.o IconFactory.cpp

main.o: main.cpp MainWindow.h \
		GameLogic.h \
		Board.h \
		Cell.h \
		util.h \
		MsButton.h \
		Player.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

NewGameDialog.o: NewGameDialog.cpp NewGameDialog.h \
		ui_NewGameDialog.h \
		util.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o NewGameDialog.o NewGameDialog.cpp

Player.o: Player.cpp Player.h \
		GameLogic.h \
		Board.h \
		Cell.h \
		util.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Player.o Player.cpp

HumanPlayer.o: HumanPlayer.cpp HumanPlayer.h \
		Player.h \
		GameLogic.h \
		Board.h \
		Cell.h \
		util.h \
		CompeteGameLogic.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o HumanPlayer.o HumanPlayer.cpp

CompeteGameLogic.o: CompeteGameLogic.cpp CompeteGameLogic.h \
		GameLogic.h \
		Board.h \
		Cell.h \
		util.h \
		Player.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o CompeteGameLogic.o CompeteGameLogic.cpp

AIPlayer.o: AIPlayer.cpp AIPlayer.h \
		Player.h \
		GameLogic.h \
		Board.h \
		Cell.h \
		util.h \
		CompeteGameLogic.h \
		MainWindow.h \
		MsButton.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o AIPlayer.o AIPlayer.cpp

moc_GameLogic.o: moc_GameLogic.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_GameLogic.o moc_GameLogic.cpp

moc_MainWindow.o: moc_MainWindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_MainWindow.o moc_MainWindow.cpp

moc_MsButton.o: moc_MsButton.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_MsButton.o moc_MsButton.cpp

moc_NewGameDialog.o: moc_NewGameDialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_NewGameDialog.o moc_NewGameDialog.cpp

moc_AIPlayer.o: moc_AIPlayer.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_AIPlayer.o moc_AIPlayer.cpp

qrc_resource.o: qrc_resource.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_resource.o qrc_resource.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

